SRC=top.v ../../bram.v ../../pancham_round.v ../../pancham.v ../../usart.v ../../generator.v

all: build/top.bit

build/top.ucf: common.ucf
	cat common.ucf > build/top.ucf

build/top.prj: $(SRC)
	rm -f build/top.prj
	for i in `echo $^`; do \
	    echo "verilog work ../$$i" >> build/top.prj; \
	done

build/top.ngc: build/top.prj
	cd build && xst -ifn ../top.xst

build/top.ngd: build/top.ngc build/top.ucf
	cd build && ngdbuild -uc top.ucf top.ngc

include common.mak

